[package]
name = "rotator"
version = "0.1.1"
authors = ["Felipe Sciammarella <fl.sciammarella@ufrj.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "^2"
pest_derive = "^2"
structopt = "0.3.9"